# Container - 01

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/csci-5409-k8s-b00988337/container-01/container1', '.']

  # Step 2: Push Docker Image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/csci-5409-k8s-b00988337/container-01/container1']

  # Step 3: Deploy Container 1 to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'c1.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster'
